apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: shiny-trigger-tracy
  namespace: work-conversation
spec:
  broker: conversation-broker
  filter:
    attributes:
      type: com.iancoffey.conversation.distracted
      subject: all
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: tracy
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: shiny-trigger-fred
  namespace: work-conversation
spec:
  broker: conversation-broker
  filter:
    attributes:
      type: com.iancoffey.conversation.distracted
      subject: all
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: fred
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: shiny-trigger-jane
  namespace: work-conversation
spec:
  broker: conversation-broker
  filter:
    attributes:
      type: com.iancoffey.conversation.distracted
      subject: all
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: jane
---
apiVersion: eventing.knative.dev/v1alpha1
kind: Trigger
metadata:
  name: shiny-trigger-peter
  namespace: work-conversation
spec:
  broker: conversation-broker
  filter:
    attributes:
      type: com.iancoffey.conversation.distracted
      subject: all
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: peter
